"""Preambulo de la version Colab del notebook consolidado.

Vive aparte porque es el unico que clona el repositorio: asi el notebook funciona
con «ejecutar todas», sin montar Drive ni subir archivos.
"""

from scripts.notebooks_contenido import code, md

PREAMBULO_FINAL_COLAB = [
    md('\n> ### Version Colab\n>\n> Pensada para ejecutarse de una vez con **Entorno de ejecucion -> Ejecutar todas**, o\n> celda por celda. La primera celda trae el proyecto; a partir de ahi todo son lecturas\n> de resultados ya calculados, asi que corre en segundos.\n>\n> **No instala nada**: solo usa `pandas`, `numpy` e `IPython`, que Colab ya trae. No hay\n> que reiniciar el entorno en ningun momento.\n'),
    code('\n# 1/2 - El proyecto: codigo, datos ya calculados y figuras.\n#\n# Se clona el repositorio, que es publico. Si no estuviera disponible se intenta una\n# copia en Drive y, como ultimo recurso, se pide subir un .zip; esos dos caminos si\n# requieren intervencion, asi que rompen el «ejecutar todas».\nimport subprocess\nimport sys\nfrom pathlib import Path\n\nREPOSITORIO = "https://github.com/JLosada-Dev/topicos-popayan.git"\nCARPETA_EN_DRIVE = "MyDrive/topicos-popayan"\nDESTINO = Path("/content/topicos-popayan")\n\n\ndef _en_colab() -> bool:\n    try:\n        import google.colab  # noqa: F401\n    except ImportError:\n        return False\n    return True\n\n\ndef _sirve(raiz) -> bool:\n    raiz = Path(raiz)\n    return ((raiz / "src" / "config.py").exists()\n            and (raiz / "data" / "processed" / "fragmentos.csv").exists())\n\n\ndef _desde_drive():\n    from google.colab import drive\n\n    drive.mount("/content/drive", force_remount=False)\n    candidata = Path("/content/drive") / CARPETA_EN_DRIVE\n    return candidata if _sirve(candidata) else None\n\n\ndef _desde_zip():\n    import zipfile\n\n    from google.colab import files\n\n    print("Sube un .zip del proyecto (debe incluir src/ y data/processed/)")\n    subidos = files.upload()\n    carpeta = Path("/content/subido")\n    with zipfile.ZipFile(next(iter(subidos))) as archivo:\n        archivo.extractall(carpeta)\n    for candidata in (carpeta, *(p.parent for p in carpeta.rglob("src/config.py"))):\n        if _sirve(candidata):\n            return candidata\n    return None\n\n\ndef obtener_proyecto() -> Path:\n    if not _en_colab():\n        aqui = Path.cwd()\n        for candidata in (aqui, *list(aqui.parents)[:2]):\n            if _sirve(candidata):\n                return candidata\n        raise RuntimeError("No se encontro el proyecto desde el directorio actual")\n\n    if _sirve(DESTINO):\n        return DESTINO\n    clonado = subprocess.run(\n        ["git", "clone", "--depth", "1", REPOSITORIO, str(DESTINO)],\n        capture_output=True, text=True,\n    )\n    if _sirve(DESTINO):\n        print("proyecto clonado del repositorio")\n        return DESTINO\n\n    print("No se pudo clonar: " + clonado.stderr.strip()[:120])\n    print("Se intenta con Drive, y si no, subiendo un zip.")\n    for alternativa in (_desde_drive, _desde_zip):\n        try:\n            raiz = alternativa()\n        except Exception as error:\n            print("  " + alternativa.__name__ + ": " + str(error)[:100])\n            continue\n        if raiz:\n            return raiz\n    raise RuntimeError("No se pudo obtener el proyecto por ninguna via")\n\n\nRAIZ = obtener_proyecto()\nsys.path.insert(0, str(RAIZ))\nprint("raiz del proyecto: " + RAIZ.name + "/")\n'),
    code('\n# 2/2 - Comprobacion: que este todo lo que el notebook va a leer\nfrom src.config import DATOS_PROCESADOS, FIGURAS\n\nNECESARIOS = (\n    "fragmentos.csv", "fragmentos_topicos.csv", "topicos_etiquetados.csv",\n    "temas_consolidado.csv", "ami_resultados.csv", "calidad_modelo.csv",\n    "cohesion_temas.csv", "dispersion_dimensiones.csv", "sensibilidad_umbral.csv",\n    "temas_baja_masa.csv",\n)\nfaltan = [n for n in NECESARIOS if not (DATOS_PROCESADOS / n).exists()]\nfiguras = len(list(FIGURAS.glob("*.png"))) if FIGURAS.exists() else 0\nprint("datos:", "completos" if not faltan else "FALTAN " + str(faltan))\nprint("figuras:", figuras)\n'),
]
